import fs from "node:fs";
import path from "node:path";
import type { OptimizationRecommendation } from "@getpromptly/shared";
import { confirm } from "../prompts.js";

/**
 * One-click apply for `promptly optimize` recommendations (Phase 7 v3).
 *
 * Turns detector output into real config — Claude Code first (richest
 * config surface), other tools get printed guidance:
 *   repetitive-workflow  → project skill (.claude/skills/<slug>/SKILL.md)
 *   repeated-corrections → marker-wrapped rule block in CLAUDE.md
 *   pre-post-action      → hook script + .claude/settings.json entry
 *   model-misuse / context-bloat → advice only (not auto-appliable)
 *
 * Every artifact carries the rec id as a marker, so re-applying is a
 * detected no-op instead of a duplicate.
 */

export interface GeneratedArtifact {
  /** Absolute target path */
  filePath: string;
  /** Content to create with, or block to append */
  content: string;
  mode: "create" | "append";
  /** Present in content/target — re-apply detection */
  marker: string;
  /** Make executable after writing */
  executable?: boolean;
}

export interface SettingsHookPatch {
  settingsPath: string;
  event: "PreToolUse" | "PostToolUse";
  hookCommand: string;
}

function slugify(parts: string[]): string {
  return parts
    .join("-")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
}

// ─── Builders (pure — covered by tests) ─────────────────────────────────────

export function buildWorkflowSkill(
  recId: string,
  sequence: string[],
  cwd: string
): GeneratedArtifact {
  const slug = slugify(sequence);
  const filePath = path.join(cwd, ".claude", "skills", slug, "SKILL.md");
  const steps = sequence.map((s, i) => `${i + 1}. \`${s}\``).join("\n");
  const content = `---
name: ${slug}
description: Run the ${sequence.join(" → ")} workflow. Use when the user asks to run this sequence or invokes /${slug}.
---

# ${sequence.join(" → ")}

Run these steps in order. Stop and report on the first failure:

${steps}

Report a one-line summary when all steps pass.

<!-- promptly:applied:${recId} -->
`;
  return { filePath, content, mode: "create", marker: `promptly:applied:${recId}` };
}

export function buildInstructionRule(
  recId: string,
  phrases: string[],
  cwd: string
): GeneratedArtifact {
  // Prefer the project root CLAUDE.md when it exists, else .claude/CLAUDE.md
  // (same convention as the auto-prompt installer)
  const rootPath = path.join(cwd, "CLAUDE.md");
  const filePath = fs.existsSync(rootPath)
    ? rootPath
    : path.join(cwd, ".claude", "CLAUDE.md");
  const marker = `promptly:rule:${recId}`;
  const bullets = phrases.map((p) => `- "${p.trim()}"`).join("\n");
  const content = `
<!-- ${marker}:start -->
## Standing correction (added by \`promptly optimize --apply\`)
You have been corrected about this repeatedly across sessions — treat it as a standing rule and apply it proactively without being asked:
${bullets}
<!-- ${marker}:end -->
`;
  return { filePath, content, mode: "append", marker };
}

export function buildHookArtifacts(
  recId: string,
  direction: "pre" | "post",
  before: string,
  after: string,
  cwd: string
): { script: GeneratedArtifact; patch: SettingsHookPatch } {
  // post: after `before` runs, run `after`  → PostToolUse, trigger=before, action=after
  // pre:  before `after` runs, run `before` → PreToolUse,  trigger=after,  action=before
  const trigger = direction === "post" ? before : after;
  const action = direction === "post" ? after : before;
  const event = direction === "post" ? "PostToolUse" : "PreToolUse";
  const slug = slugify([direction, trigger, action]);
  const scriptPath = path.join(cwd, ".claude", "hooks", `promptly-${slug}.sh`);

  const content = `#!/bin/bash
# Generated by \`promptly optimize --apply\` — rec: ${recId}
# Runs \`${action}\` automatically ${direction === "post" ? "after" : "before"} \`${trigger}\` Bash commands.
# marker: promptly:applied:${recId}
input=$(cat)
cmd=$(printf '%s' "$input" | node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{try{process.stdout.write(JSON.parse(d).tool_input?.command??"")}catch{}})')
case "$cmd" in
  "${trigger}"*)
    ${action}
    ;;
esac
exit 0
`;
  return {
    script: {
      filePath: scriptPath,
      content,
      mode: "create",
      marker: `promptly:applied:${recId}`,
      executable: true,
    },
    patch: {
      settingsPath: path.join(cwd, ".claude", "settings.json"),
      event,
      hookCommand: `"$CLAUDE_PROJECT_DIR"/.claude/hooks/promptly-${slug}.sh`,
    },
  };
}

/** Merge a hook entry into project settings. Returns false when already present. */
export function mergeHookIntoSettings(patch: SettingsHookPatch): boolean {
  let settings: Record<string, unknown> = {};
  if (fs.existsSync(patch.settingsPath)) {
    settings = JSON.parse(fs.readFileSync(patch.settingsPath, "utf-8"));
  }
  const hooks = (settings.hooks ??= {}) as Record<string, unknown[]>;
  const entries = (hooks[patch.event] ??= []) as Array<{
    matcher?: string;
    hooks?: Array<{ type: string; command: string }>;
  }>;

  const present = entries.some((e) =>
    e.hooks?.some((h) => h.command === patch.hookCommand)
  );
  if (present) return false;

  entries.push({
    matcher: "Bash",
    hooks: [{ type: "command", command: patch.hookCommand }],
  });
  fs.mkdirSync(path.dirname(patch.settingsPath), { recursive: true });
  fs.writeFileSync(patch.settingsPath, JSON.stringify(settings, null, 2) + "\n");
  return true;
}

/** Write one artifact. Returns false when the marker shows it was already applied. */
export function writeArtifact(artifact: GeneratedArtifact): boolean {
  if (fs.existsSync(artifact.filePath)) {
    const existing = fs.readFileSync(artifact.filePath, "utf-8");
    if (existing.includes(artifact.marker)) return false;
    if (artifact.mode === "create") {
      // a different file already lives there — do not clobber
      throw new Error(
        `${artifact.filePath} already exists and was not generated from this recommendation. Remove or rename it first.`
      );
    }
    fs.writeFileSync(
      artifact.filePath,
      existing + (existing.endsWith("\n") ? "" : "\n") + artifact.content
    );
  } else {
    fs.mkdirSync(path.dirname(artifact.filePath), { recursive: true });
    fs.writeFileSync(artifact.filePath, artifact.content.replace(/^\n/, ""));
  }
  if (artifact.executable) fs.chmodSync(artifact.filePath, 0o755);
  return true;
}

// ─── Orchestration ──────────────────────────────────────────────────────────

function rel(p: string): string {
  const r = path.relative(process.cwd(), p);
  return r.startsWith("..") ? p : r;
}

function uniquePhrases(rec: OptimizationRecommendation): string[] {
  const phrases = rec.evidence
    .filter((e) => e.kind === "repeated-correction")
    .map((e) => (e as { originalPhrase: string }).originalPhrase);
  return [...new Set(phrases)].slice(0, 3);
}

export async function applyRecommendation(
  rec: OptimizationRecommendation,
  cwd = process.cwd()
): Promise<void> {
  const artifacts: GeneratedArtifact[] = [];
  let patch: SettingsHookPatch | null = null;

  switch (rec.type) {
    case "repetitive-workflow": {
      const sequence = rec.details?.sequence as string[] | undefined;
      if (!sequence?.length) throw new Error("Recommendation has no workflow sequence to apply.");
      artifacts.push(buildWorkflowSkill(rec.id, sequence, cwd));
      break;
    }
    case "repeated-corrections": {
      const phrases = uniquePhrases(rec);
      if (phrases.length === 0) throw new Error("Recommendation has no correction phrases to apply.");
      artifacts.push(buildInstructionRule(rec.id, phrases, cwd));
      break;
    }
    case "pre-post-action": {
      const { direction, before, after } = (rec.details ?? {}) as {
        direction?: "pre" | "post";
        before?: string;
        after?: string;
      };
      if (!direction || !before || !after) throw new Error("Recommendation is missing hook details.");
      const built = buildHookArtifacts(rec.id, direction, before, after, cwd);
      artifacts.push(built.script);
      patch = built.patch;
      break;
    }
    case "model-misuse":
      console.log(`"${rec.title}" can't be auto-applied — model choice lives in your AI tool.`);
      console.log("  Claude Code: /model (or ANTHROPIC_MODEL env) — try the cheaper tier on short, well-specified tasks.");
      console.log("  The evidence sessions above show where the cheaper model would likely have sufficed.");
      return;
    case "context-bloat":
      console.log(`"${rec.title}" can't be auto-applied — it's a workflow habit, not a config.`);
      console.log("  Split token-heavy work into smaller scoped sessions before the context saturates;");
      console.log("  start a fresh session per sub-task instead of pushing through compactions.");
      return;
    default:
      throw new Error(`Don't know how to apply recommendation type "${rec.type}".`);
  }

  console.log(`Applying: ${rec.title}\n`);
  for (const a of artifacts) {
    console.log(`--- ${a.mode === "append" ? "append to" : "create"} ${rel(a.filePath)} ---`);
    console.log(a.content.trim());
    console.log("");
  }
  if (patch) {
    console.log(`--- ${rel(patch.settingsPath)}: add ${patch.event} hook ---`);
    console.log(`${patch.event} → Bash → ${patch.hookCommand}\n`);
  }

  const ok = await confirm({
    message: `Apply ${artifacts.length + (patch ? 1 : 0)} change(s)?`,
    default: true,
  });
  if (!ok) {
    console.log("Aborted — nothing written.");
    return;
  }

  let wrote = 0;
  for (const a of artifacts) {
    if (writeArtifact(a)) {
      console.log(`  ${rel(a.filePath)} ✓`);
      wrote++;
    } else {
      console.log(`  ${rel(a.filePath)} — already applied, skipped`);
    }
  }
  if (patch) {
    if (mergeHookIntoSettings(patch)) {
      console.log(`  ${rel(patch.settingsPath)} ✓`);
      wrote++;
    } else {
      console.log(`  ${rel(patch.settingsPath)} — hook already present, skipped`);
    }
  }

  if (wrote > 0) {
    console.log("\nApplied. Restart your AI tool to pick up the new config.");
  }
}
